# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
apt_packages:
  - librabbitmq-dev
  # For integration testing.
  - rabbitmq-server
r_binary_packages:
  - later
  - Rcpp
  - testthat
before_script:
  - sudo systemctl start rabbitmq-server
before_deploy: Rscript -e "install.packages('pkgdown')"
deploy:
  provider: script
  script: Rscript -e "pkgdown::deploy_site_github()"
  skip_cleanup: true
